### ISSUE TITLE
Error: Cannot find module '../build/Release/textdetector'

### ISSUE THREAD

**Issue by xinshouke** [pranavjha/text-detector#7]
I run the test cases, the below error was throw:
Error: Cannot find module '../build/Release/textdetector'.
Would you like tell me how to build the textdetector using those source code please?  I had installed tesseract and openCV first.

**Comment by xinshouke** [comment]
I was tring to build the c++ codes

**Comment by pranavjha** [comment]
@xinshouke sorry for the delay in response. This module is not ready yet, so it won't work. It will take me some time to complete it. I had to put it on hold, but i am planning to release it by the end of november.
